#
#============================================================================
#
#                                 DOOM Retro
#           The classic, refined DOOM source port. For Windows PC.
#
#============================================================================
#
#    Copyright © 1993-2026 by id Software LLC, a ZeniMax Media company.
#    Copyright © 2013-2026 by Brad Harding <mailto:brad@doomretro.com>.
#
#    This file is a part of DOOM Retro.
#
#    DOOM Retro is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by the
#    Free Software Foundation, either version 3 of the license, or (at your
#    option) any later version.
#
#    DOOM Retro is distributed in the hope that it will be useful, but
#    WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#    General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with DOOM Retro. If not, see <https://www.gnu.org/licenses/>.
#
#    DOOM is a registered trademark of id Software LLC, a ZeniMax Media
#    company, in the US and/or other countries, and is used without
#    permission. All other trademarks are the property of their respective
#    holders. DOOM Retro is in no way affiliated with nor endorsed by
#    id Software.
#
#============================================================================
#

name: DOOM Retro

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: scripts/build.sh clean

  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [32-bit, 64-bit]
        configuration: [Release]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore msvc\doomretro.sln

      - name: Build
        run: msbuild msvc\doomretro.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} /p:PlatformToolset=v143 /m

      - name: Copy WAD file
        run: copy res\doomretro.wad bin\${{ matrix.platform }}\${{ matrix.configuration }}\
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: doomretro-${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            bin/${{ matrix.platform }}/${{ matrix.configuration }}/*.exe
            bin/${{ matrix.platform }}/${{ matrix.configuration }}/*.dll
            bin/${{ matrix.platform }}/${{ matrix.configuration }}/*.wad
